#! /bin/zsh
local cmd cmd_file code
cmd_file=$(mktemp)
if broot --outcmd "$cmd_file" "$@"; then
    cmd=$(<"$cmd_file")
    rm -f "$cmd_file"
    eval "$cmd"
    zle reset-prompt
else
    code=$?
    rm -f "$cmd_file"
    return "$code"
fi
